// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mycompany.nearestcab.domain;

import com.mycompany.nearestcab.domain.CabIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CabIntegrationTest_Roo_Configurable {
    
    declare @type: CabIntegrationTest: @Configurable;
    
}
